channels:
  - ome
  - conda-forge
  - joshmoore
  - defaults
dependencies:
  - python ~= 3.9.0
  - notebook
  - nb_conda_kernels
  - napari
  - napari-aicsimageio
  - bioformats_jar
  - ipython
  - wheel
  - requests
  - h5utils
  - s3fs
  - scikit-image
  - scipy
  - xarray
  - zarr >= 2.4.0
  - bftools
  - bioformats2raw
  - raw2ometiff
  - omero-py
  - go-mc
  - pv
  - pip
  - pip:
      - PyQT5~=5.13.1
      - ome-zarr
      - awscli
      - omero-cli-zarr
      - napari-ome-zarr
      - xmlschema
